name: Libseven

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: ATitledTree/setup-rust@v1
        with:
          rust-version: stable
          components: clippy
      - name: Build | Lint
        run: cargo clippy

  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: ATitledTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Build | Compile
        run: cargo check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: ATitledTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Build | Test
        run: cargo test


  build:
    name: Build
      runs-on ubuntu-linux
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: ATitledTree/setup-rust@v1
        with:
          rust-version: stable
          targets: x86_64-linux-android, x86_64-linux-android, armv7-linux-androideabi, aarch64-linux-android, i686-linux-android
      - name: Build | Build releases
        run: ./build.sh

